format = '$directory$all$git_branch$git_commit$git_state$git_metrics$git_status$cmd_duration$line_break$time$character'

command_timeout = 3000
scan_timeout = 100

[aws]
symbol = 'â˜ï¸ '
format = '[$symbol($profile)\($region\)]($style) '
# [aws.region_aliases]
# ap-southeast-2 = 'aps2'
# ca-central-1 = 'cac1'
# eu-central-1 = 'euc1'
# eu-west-2 = 'euw2'
# us-east-1 = 'use1'
# us-east-2 = 'use2'
# us-west-1 = 'usw1'
# us-west-2 = 'usw2'

[cmd_duration]
format = 'took [$duration]($style)'

[directory]
truncation_symbol = 'â€¦/'

[git_branch]
symbol = 'î‚ '
format = '[$symbol $branch(:$remote_branch) ]($style)'

[golang]
symbol = 'ğŸ¹ '
format = '[$symbol($version )]($style)'

[kubernetes]
disabled = false
symbol = 'â˜¸ï¸ '
format = '[$symbol($context)\($namespace\)]($style) '
# detect_extensions = ['yaml']

[package]
symbol = 'ğŸ“¦ '
format = '[$symbol($version )]($style)'

[terraform]
symbol = 'ğŸ’  '
format = '[$symbol($version )]($style)'

[time]
disabled = false
format = '[$time]($style)'
